### ISSUE TITLE
error message when changing active version (for homework with no automated testing?)

### ISSUE THREAD

**Issue by bmcutler** [RCOS-Grading-Server/HWserver#232]
Details:
     Notice: Undefined index: testcases in /usr/local/hss/website/public/controller/data_functions.php on line 688
     After changing active version from v2 to v1.

NOTE:  There may be some other errors for assignment configurations with no test cases.

**Comment by MasterOdin** [comment]
Okay, replicated this using Stacy's class (will get config files and necessary details to reproduce on local box.

The current notice is:
> Notice: Undefined index: testcases in /usr/local/hss/website/public/controller/data_functions.php on line 737
> 
> Notice: Undefined index: testcases in /usr/local/hss/website/public/controller/data_functions.php on line 737
> 
> Notice: Undefined index: testcases in /usr/local/hss/website/public/controller/data_functions.php on line 737

The easiest fix is doing something like:
``` if (isset($version_results['testcases']))``` on line 736. 

Though the entire function (get_homework_tests)[https://github.com/RCOS-Grading-Server/HWserver/blob/master/public/controller/data_functions.php#L733-L775] should be rewritten as right now the nested for loop is completely unnecessary and wasteful (as instead of nested for loops, we want to use (array_search)[http://php.net/manual/en/function.array-search.php] for better runtime speed (not much, but some).
